version: '3.8'
services:

  webstash-api:
    build:
      context: web-stash
      dockerfile: Dockerfile.layered
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://webstash-db:5432/webstashdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "18080:8080"
    restart: always
    depends_on:
    - webstash-db

  webstash-ui-nextjs:
    container_name: webstash-ui-nextjs
    build:
      context: webstash-ui-nextjs
      dockerfile: Dockerfile
    ports:
      - "13000:3000"
    environment:
      SERVER_SIDE_API_BASE_URL: http://webstash-api:8080
      CLIENT_SIDE_API_BASE_URL: http://localhost:18080
