apiVersion: v1
kind: Service
metadata:
  name: webstash-api-svc
spec:
  type: NodePort
  selector:
    app: webstash-api-pod
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webstash-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webstash-api-pod
  template:
    metadata:
      labels:
        app: webstash-api-pod
    spec:
      containers:
        - name: webstash
          image: akashpal14/webstash-back-jib
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: postgres_host
                  name: webstash-config
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: postgres_port
                  name: webstash-config
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: postgres_dbname
                  name: webstash-config
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: postgres_username
                  name: webstash-secrets
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres_password
                  name: webstash-secrets
