name: Build

on:
  push:
    branches: [ "**" ]

jobs:
  build-webstash-back:
    name: Build-webstash-back

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web-stash

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Change maven wrapper permissions
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw verify

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          ./mvnw clean package jib:dockerBuild -DskipTests
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/webstash-back-jib
          
  build-webstash-ui:
    name: Build webstash-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webstash-ui-nextjs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: webstash-ui-nextjs/package-lock.json
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/webstash-ui-nextjs .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/webstash-ui-nextjs